server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingservice
    username: hbstudent
    password: hbstudent

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update